#! /usr/bin/ruby

VOICES = [:ralph, :junior, :princess, :kathy, :bruce, :zarvox, :deranged, :fred]
WORDS = ['hi', 'there', 'this', 'is', 'a', 'or', 'that', 'what', 'lol', 'banana', 'taco', 'flamingo', 'earphones', 'coffee', 'television', 'aliens', 'twerk', 'music', 'revolutionary', 'disco', 'tango', 'tea', 'peas', 'please', 'tickle', 'robot', 'activate']

words = []
(Random.rand(10) + 1).times do
  words << WORDS.sample
end

voice = VOICES.sample
sentence = words.join(' ')

puts sentence
system "say -v #{voice} #{sentence}"
